### ISSUE TITLE
struggling to install

### ISSUE THREAD

**Issue by samlipworth** [samhorsfield96/ggCaller#1]
Tried installing with Conda - everything seems to work but the I get an "Illegal instruction" error when I try to run.

Then tried installing from source - get an error about gcc version but I don't understand this because `gcc --version` gives 12.2.0

Very keen to try this out so would be grateful for your help.

Thanks.

**Comment by samhorsfield96** [comment]
Hi Sam, I'm aware of this issue with the conda install. This is due to dependency issues in the conda recipe that aren't yet resolved, so installing from source is the best way forward at this time. 

How did you install from source, and which operating system are you using? The best way is still using conda, setting up the conda environment using "environment_linux.yml".  Unfortunately only linux is supported currently.

**Comment by samlipworth** [comment]
Yeh it was on an Ubuntu cluster - I think the issue is the GCC version but the version looks OK as above - anyway I'll try again on my local machine (also ubuntu) and let you know.

**Comment by samlipworth** [comment]
your tip to install gcc form conda worked, thanks! - https://anaconda.org/conda-forge/cxx-compiler
